version: '3'
services:
  hybrid-agi-db:
    image: falkordb/falkordb:edge
    container_name: hybrid-agi-db
    ports:
      - 6379:6379
      # - 3000:3000
  hybrid-agi-db-browser:
    image: redislabs/redisinsight:1.14.0
    container_name: hybrid-agi-db-browser
    depends_on:
      - hybrid-agi-db
    ports:
      - 8001:8001
  hybrid-agi-sandbox:
    image: hybrid-agi-sandbox
    working_dir: /Workspace
    build:
      context: ./sandbox
      dockerfile: Dockerfile
    container_name: hybrid-agi-sandbox
    ports:
      - 8000:8000